
server:
  port: 8088
  
spring:
  application:
    name: synclistener
    
api:
  url: http://localhost:8084/syncmessage/getCurrentTime
    
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8083/eureka/
   