server:
  port: 8087
  
spring:
  application:
    name: syncmessanger
    
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8083/eureka/
   
   
hystrix:
  command:
   syncmessanger:
    execution:
     isolation:
      thread:
       timeoutInMilliseconds: 1000000 