#spring.application.name=discovery-server
#server.port=8083
#eureka.instance.hostname=localhost
#eureka.client.serviceUrl.defaultZone=http://localhost:8083/eureka/
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false

spring:  application:    name: discovery-server
 
server:  port: 8083
 
eureka:  instance:    hostname: localhost
  
  client:    serviceUrl:
     defaultZone: http://localhost:8083/eureka/
     
    register-with-eureka: false
    fetch-registry: false    
           
              